flower_api_marketing_contactlist_findcontactsby:
    path:     /contactlist/{id}/contacts
    defaults: { _controller: FlowerMarketingBundle:Api\ContactList:getByContactList }
    methods: [GET]

flower_api_marketing_contactlist_availables:
    path:     /availables
    defaults: { _controller: FlowerMarketingBundle:Api\ContactList:getAvailables }
    methods: [GET]