<?php

namespace Flower\MarketingBundle\Repository;

use Doctrine\DBAL\Driver\Statement;
use Doctrine\ORM\EntityRepository;

/**
 * CampaignEmailMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignEmailMessageRepository extends EntityRepository
{

    public function getCountByCampaign($campaignId)
    {
        $qb = $this->createQueryBuilder("m");
        $qb->select("COUNT(m)");
        $qb->where("m.campaign = :campaign_id")->setParameter(":campaign_id", $campaignId);

        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function getOpensByCampaign($campaignId)
    {
        $qb = $this->createQueryBuilder("m");
        $qb->select("SUM(m.opens)");
        $qb->where("m.campaign = :campaign_id")->setParameter(":campaign_id", $campaignId);

        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function getClicksByCampaign($campaignId)
    {
        $qb = $this->createQueryBuilder("m");
        $qb->select("SUM(m.clicks)");
        $qb->where("m.campaign = :campaign_id")->setParameter(":campaign_id", $campaignId);

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function prepareRawInsert()
    {
        $statement = "INSERT INTO "
                . "campaign_mail_message(providerId, campaign_mail_id, sender, toemail, opens, clicks, state) "
                . "VALUES(:providerId, :campaign_mail_id, :sender, :toemail, :opens, :clicks, :state)";

        $conn = $this->getEntityManager()->getConnection();

        $stmt = $conn->prepare($statement);

        return $stmt;
    }

    public function rawInsert(Statement $stmt, $providerId, $campaignMailId, $sender,$toEmail, $state, $opens = 0, $clicks = 0)
    {
        $stmt->bindParam("providerId", $providerId);
        $stmt->bindParam("campaign_mail_id", $campaignMailId);
        $stmt->bindParam("sender", $sender);
        $stmt->bindParam("toemail", $toEmail);
        $stmt->bindParam("opens", $opens);
        $stmt->bindParam("clicks", $clicks);
        $stmt->bindParam("state", $state);

        $stmt->execute();
    }

    public function getPageCountByCampaignId($campaignId, $pageSize)
    {
        $count = $this->getCountByCampaign($campaignId);
        return ceil($count / $pageSize);
    }

    public function getByCampaignPaged($campaignId, $offset, $limit)
    {
        $qb = $this->createQueryBuilder("m");
        $qb->where("m.campaign = :campaign_id")->setParameter("campaign_id", $campaignId);

        $qb->setFirstResult($offset);
        $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

}

