<?php

namespace Flower\MarketingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CampaignMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignMailRepository extends EntityRepository
{
    public function getCountEnabled()
    {
        $qb = $this->createQueryBuilder("cm");
        $qb->select("COUNT(cm)");
        $qb->where("cm.enabled = :enabled")->setParameter("enabled", true);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
