<?php

namespace Flower\MarketingBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ContactListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactListRepository extends EntityRepository
{
    
    
    
    public function getContacts($contactListId, $offset, $limit)
    {
        $qb = $this->createQueryBuilder("cl");
        $qb->select("c");
        $qb->innerJoin("cl.contacts", "c", Join::WITH, "cl.id = :contact_list_id");
        $qb->where("cl.id = :contact_list_id");
        $qb->setParameter("contact_list_id", $contactListId);

        return $qb->getQuery()->getResult();
    }

}
